# This action tests and builds the mimic iii website

name: build-mimiciii-website
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build
      run: hugo
